### ISSUE TITLE
Why is not the project being built?

### ISSUE THREAD

**Issue by gHashTag** [rationalappdev/react-native-navigation-tutorial#1]
Why is not the project being built?
Maybe because I'm doing the project without expo?
![simulator screen shot 17 2017 16 33 06](https://user-images.githubusercontent.com/6774813/28270306-a5932be4-6b0d-11e7-895f-b7e6a0e72445.png)

**Comment by rafael-trevisan** [comment]
@gHashTag I followed exactly the instructions and I got it done without any issue. I used CRNA (Expo)
